version: '3'

services:
  # ---------------------------
  # prometheus
  # ---------------------------
  prometheus:
   image: prom/prometheus
   container_name: prometheus
   ports:
    - 9090:9090
   volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml

  pipeline:
    image: skymind/pipelines:1.2.1
    ports:
     - 65322:65322
    volumes:
     - ./config.json:/usr/share/config.json
    entrypoint:
     - java
     - -cp
     - /srv/pipelines.jar
     - ai.skymind.pipelines.configprovider.PipelineServerMain
     - --configPath
     - /usr/share/config.json
     - --verticleClassName
     - ai.skymind.pipelines.verticles.inference.InferenceVerticle

  # ---------------------------
  # grafana
  # ---------------------------
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password

